### ISSUE TITLE
一個問題

### ISSUE THREAD

**Issue by drduan** [leelit/STUer-client#3]
你覺得用mvp 對 編程有什麼好處啊？

**Comment by leelit** [comment]
首先我想说的是这个是我个人理解的MVP- -，我觉得网上的文章千千万万，貌似也没有完全一样的编码风格，在我做这个项目的过程中google出了官方的mvp写法推荐，以后可能遵循者会比较多。
然后，我实践下来，感觉有两个好处比较明显：1、开发起来比原本快一点，虽然代码会写多一点，但是写起来比较顺手。2、定位问题比较快，因为模块之间的职责更清晰了。

**Comment by drduan** [comment]
哦
